### ISSUE TITLE
InputGroup causes error

### ISSUE THREAD

**Issue by rsaccon** [alphadito/nodetree_script#2]
I started on a larger example using nodetree, everything worked great until I tried to use `InputGroup` subclasses. The error I got is listed below

```python
Error: Python: Traceback (most recent call last):
  File "/curved_house.py", line 18, in <module>
  File "/Users/robertosaccon/Library/Application Support/Blender/3.6/scripts/addons/nodetree_script/api/nodetree.py", line 263, in nodetree
    return node_tree_class(node_tree_name,**kwargs).build_tree(builder)
  File "/Users/robertosaccon/Library/Application Support/Blender/3.6/scripts/addons/nodetree_script/api/nodetree.py", line 54, in build_tree
    self.set_input_sockets()
  File "/Users/robertosaccon/Library/Application Support/Blender/3.6/scripts/addons/nodetree_script/api/nodetree.py", line 139, in set_input_sockets
    self.set_tree_input(i,input_info)
  File "/Users/robertosaccon/Library/Application Support/Blender/3.6/scripts/addons/nodetree_script/api/nodetree_blender3.py", line 36, in set_tree_input
    tree_input.default_value = input_info.default_value
TypeError: bpy_struct: item.attr = val: NodeSocketInterfaceFloat.default_value expected a float type, not tuple
```

I am on Blender 3.6.5 and using the nodetree version just before you added the Node-to-Script-inClipboard operator.

**Comment by rsaccon** [comment]
Ups, my bad, sorry, all is nearly perfekt. I had by mistake a `,` somewhere in my `InputGroup` subclass, turning it unintentionally in a tuple.

However there is no Syntax highlighting in Visual Code for `InputGroup`.
If I check the tyepshed folder in the addodn, there is no `static` content:
```shell
(py310) (base) robertosaccon@MacBook-Pro api % pwd
/Users/robertosaccon/Library/Application Support/Blender/3.6/scripts/addons/nodetree_script/typeshed/nodetree_script/api
(py310) (base) robertosaccon@MacBook-Pro api % ls
dynamic
``` 
But there is probably just something messed up with my setup.

**Comment by rsaccon** [comment]
Ok, trying to make sure my setup is not messed up somehow. In Blender I uninstalled nodetree_script und installed a zip from the latest main branch. Restarted Blender, restarted VS Code, made sure the typeshed path is correct. Now I have the following situation:

all nodetree_script methods have the correct type hints, but all nodetree_script classes are displayed as "not defined" (the yellow wavelike underline). My import statements look like this:
```python
from nodetree_script import *
from nodetree_script.api.dynamic.geometry import *
```
if I import the classes explicitly, then the type hints work fine.

**Comment by alphadito** [comment]
@rsaccon good catch! The nodesocket subclasses for annotations and the extra functions for each math operation are now included in the typeshed. This should remove the undefined warnings.

**Comment by rsaccon** [comment]
Great, thanks. Now things look better, except for the `InputGroup`, that has still no type hints:
![Screenshot 2023-12-24 at 00 24 45](https://github.com/alphadito/nodetree_script/assets/16122/79862a58-845f-48be-8115-4b1684eed802)

**Comment by alphadito** [comment]
Ah ok the offending line in the `__init__.py` typeshed file was this import statement 

```python 
from .static.input_group import InputGroup 
```

which I guess conflicts with the InputGroup class stub. All import statements have been removed to resolve similar issues.

**Comment by rsaccon** [comment]
Now all looks perfect, thanks. Closing this.
