### ISSUE TITLE
switch nodes in geometry and compositor script should be distinguished  

### ISSUE THREAD

**Issue by smj97** [alphadito/nodetree_script#3]
hello I was searching for all blender nodes scripting API and I finally found your good work!

I appreciate your work a lot 

but when I used switch node in @geometryscript, it took as switch node in "compositor" node not in geometry switch node.

I guess they should have different function name to be distinguished

Thank you for readingg!

<img width="480" alt="geometrytree_switchnode" src="https://github.com/alphadito/nodetree_script/assets/55137878/f44ff3ab-f491-4044-8591-a89089a87896">
<img width="350" alt="geometrytree_switchnode1" src="https://github.com/alphadito/nodetree_script/assets/55137878/3f5466ca-33d0-4372-81c6-a195677de701">

**Comment by alphadito** [comment]
If two different node tree types have nodes with the same name you should be able to switch between them with imports.
```python
from nodetree_script.api.dynamic.geometry import *
@geometrytree
def somegeo():
    return switch()

from nodetree_script.api.dynamic.compositor import *
@compositortree
def somecomp():
    return switch()
```
